### ISSUE TITLE
Что нужно пофиксить 

### ISSUE THREAD

**Issue by ghost** [alex-pat/yasm-tool#2]
По моделям:

1. User -- убрать дублирование в find_for_oauth и заменить p на puts, хоть это и руби, но больше смахивает на опечатку. 
2.  Page -- тернарный оператор в update_component не прибавляют читабельности и уму, лучше вынести в if, set_url не влез в экран, надо разбить на пару строк.
3. Ability -- вытереть уже не нужные комментарии и сгенерированный док. 

По контроллерам:

1. Sites -- есть 3 метода с одинаковой логикой, но разными данными, было бы неплохо вынести данные в параметры одного метода.

**Comment by alex-pat** [comment]
Closed
